apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-todo
spec:
  template:
    metadata:
      labels:
        version: green
    spec:
      containers:
      - name: fastapi
        image: your-image:green

