apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-blue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KangNaewon/gitops-deploy
    targetRevision: HEAD
    path: app/overlays/blue
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
